name: Psalm Static analysis

on: [push, pull_request]

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Mark workspace as safe
        run: git config --global --add safe.directory /github/workspace

      - name: Psalm
        uses: docker://ghcr.io/psalm/psalm-github-actions
        with:
              ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
