name: Psalm Static analysis

on: [push, pull_request]

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
              set-safe-directory: /github/workspace

      - name: Mark workspace as safe
        run: |
              git config --global --add safe.directory /github/workspace
              git config --global --add safe.directory /home/runner/work/test-psalm/test-psalm
    
      - name: Check the data
        run: echo $GITHUB_WORKSPACE

      - name: Psalm
        uses: docker://ghcr.io/psalm/psalm-github-actions
        with:
              ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
