name: Psalm Static analysis

on: [push, pull_request]

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Mark the directory as safe for Git
        run: |
          git config --global --add safe.directory /github/workspace
          git config --global --get-all safe.directory

      - name: Psalm
        uses: docker://ghcr.io/psalm/psalm-github-actions
